### ISSUE TITLE
Infinite loop on scope resolution

### ISSUE THREAD

**Issue by dare-to-recurse** [NishanthSpShetty/crust#12]
I found an issue where your code seems to go into an infinite loop trying to resolve a token.

After debugging it I believe it's getting stuck on "Entity::" in the operator== overload line in the cpp file provided below

I'm invoking the command as follows

```
$ crust
Enter the C/C++ file to be converted to Rust : Entity.cpp
Enter the translation mode [(S/s)trict/(L/l)oose] : S
Do you want to create a cargo project :[Y/N]N
Input file size : 126bytes
```

At which point it seemingly gets stuck utilizing 100% of one cpu core on my computer.
Running it with loose mode behaves the same.

Here is a minimal piece of code that shows the same issue
entity.hpp:
```c++
#include <cstdint>
namespace test
{
	class Entity
	{
	public:
		bool operator==(const Entity& other) const;
	private:
		std::size_t mId;
	};
}
```

entity.cpp:
```c++
#include <entity.hpp>
using namespace test;
bool Entity::operator==(const Entity& other) const
{
	return mId == other.mId;
}
```

**Comment by NishanthSpShetty** [comment]
Hey, thank you for reporting, currently crust doesn't support these language construct from C++, I would like to have this in crust but haven't been able to  spend much time on it.

**Comment by NishanthSpShetty** [comment]
I have addressed infinite looping in parser. It's able to transpile the entity.cpp. But to parse header it must support namespace and function declaration. Currently these are out of the crust capability.

**Comment by dare-to-recurse** [comment]
Thanks for the quick feedback and fix.

I did assumed those language constructs weren't supported at the moment, I just didn't expect the looping to happen.

**Comment by NishanthSpShetty** [comment]
I admit it was naive implementation, without giving much thought on future plans and quality of code itself.
