### ISSUE TITLE
Error on every file: index out of bounds

### ISSUE THREAD

**Issue by n8henrie** [NishanthSpShetty/crust#15]
Hello,

I had read about crust a while ago and was looking forward to a reason to try it out!

Unfortunately, I'm not having any luck using it on a fairly small C++ project: <https://github.com/wez/atomicparsley>

On nearly every file in the codebase, I get an `index out of bounds` error:

```console
$ crust src/uuid.cpp 
Input file size : 16474bytes 
TokenizingInvoking Parser....
thread 'main' panicked at 'index out of bounds: the len is 1539 but the index is 1539', src/library/parser/parser.rs:655:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It does succeed on e.g. `array.rs`, as well as a `hello_world.cpp` that I tried it on.

Is there a general workflow for me to figure out what the issue may be with these files?

**Comment by NishanthSpShetty** [comment]
@n8henrie Hi, thank you for raising the issue, the previous issue opened in crust is also same as this one. 
TBH I dint do great job with this project back then, I have been meaning to revamp and improve, though unable to find time.

The parser goes through the tokens expecting set of constructs which I knew at the time of writing the project and chose sub-set of language for the project.
There are language construct which are unknown to parser which makes certain statement shorter than expected which fails when parser tries to read next expected token.

For ex:
```
a = a+10;
```
here if parser assumed there will be a expression of 3 tokens on RHS, and actual expression happens to be, as follows
```
a+=10
```
so to read 10, parser access 4th token in tokens list (index starting from 0), as the expression is shorter it will fail.

**Comment by n8henrie** [comment]
Ah okay, that makes sense!

Sounds like I would need much greater knowledge of C++ to be able to work around, so I'll close the issue for now. Thanks for the quick response!
